{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "db425733_ef46f077",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 7,
      "author": {
        "id": 220
      },
      "writtenOn": "2022-06-15T19:44:11Z",
      "side": 1,
      "message": "CI is failing, is it normal or does it need adaptation too?",
      "range": {
        "startLine": 5,
        "startChar": 37,
        "endLine": 7,
        "endChar": 31
      },
      "revId": "824048cc010f7ca03c9d6eae2cfa86e7e3ae36af",
      "serverId": "1e26b4c1-6b8c-47ff-9df7-501b633d3b5a"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "c830cc0e_392eeff3",
        "filename": "build.py",
        "patchSetId": 2
      },
      "lineNbr": 217,
      "author": {
        "id": 220
      },
      "writtenOn": "2022-06-15T19:44:11Z",
      "side": 1,
      "message": "remove",
      "range": {
        "startLine": 212,
        "startChar": 14,
        "endLine": 217,
        "endChar": 7
      },
      "revId": "824048cc010f7ca03c9d6eae2cfa86e7e3ae36af",
      "serverId": "1e26b4c1-6b8c-47ff-9df7-501b633d3b5a"
    }
  ]
}